import sys
texto = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pulvinar, libero vitae imperdiet luctus, lorem dui dapibus mi, vitae blandit neque urna vitae elit. Integer eu finibus dolor. Ut eleifend arcu sit amet felis gravida pulvinar. Vivamus semper nisi tellus, convallis lobortis leo mollis a. Sed at dignissim elit. Curabitur accumsan eu leo ac maximus. Morbi sollicitudin, sem vitae sodales dictum, elit nulla vehicula turpis, quis euismod nulla orci in massa.\nNam enim magna, ultricies eget varius sit amet, sagittis dignissim nulla. Quisque finibus pellentesque velit ut lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum convallis magna risus, eu euismod massa tincidunt quis. Curabitur mauris arcu, convallis ut ornare posuere, aliquam at purus. Vestibulum a sagittis nulla, eu semper eros. Suspendisse vel placerat eros, ultricies molestie eros.\nIn hac habitasse platea dictumst. Vivamus quis libero ligula. Aliquam erat volutpat. Morbi at justo nisi. Fusce gravida dapibus nulla, nec fringilla mauris ornare vel. Nam enim justo, interdum et mauris nec, faucibus finibus diam. Proin viverra ex id orci pellentesque, non porttitor nunc lacinia. Sed nec tellus est. Quisque metus erat, aliquet et purus eget, volutpat lacinia dolor. Vivamus et eros turpis. Cras suscipit elementum viverra. In volutpat erat vel lorem ornare condimentum a sit amet justo. Fusce et nunc et lacus auctor laoreet. Duis pretium, eros eget elementum efficitur, felis metus dictum augue, sit amet maximus arcu metus eget mauris.\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse id venenatis elit, sit amet bibendum neque. Vivamus dignissim dapibus nulla id tempor. Curabitur ac orci arcu. Phasellus a commodo risus. Fusce dapibus in eros vitae tempus. Nam gravida fringilla orci eget consectetur. Phasellus placerat elit vel urna dapibus, vitae dictum mi aliquam. Nunc vitae pulvinar mi. Mauris eleifend dui id pellentesque viverra. Curabitur posuere, nisi ac lacinia porttitor, lectus risus iaculis ipsum, in suscipit sem velit ac purus. Nulla iaculis et lorem et facilisis. Mauris eu facilisis nisl, eu blandit massa. Proin et porta tortor, ac aliquam eros. Sed dapibus, quam sed tempus ornare, velit quam eleifend justo, id sodales neque nulla sed tortor. Cras accumsan aliquet varius.\nDuis ut scelerisque mi. Fusce id elit felis. Ut quis lorem ut orci aliquet semper. Mauris aliquet ipsum nulla, eget cursus ex fermentum sed. Suspendisse dapibus volutpat ex vel fringilla. Ut pellentesque ac nisi non lobortis. In venenatis erat justo, quis aliquam nulla aliquam ac. Sed at urna vel justo porta euismod in nec nunc."
parrafos = int(sys.argv[1])
lista = texto.split("\n")
i=0
while i < parrafos:
    print (lista[i])
    i = i+1


